# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20171107_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedJobs',
            fields=[
                ('job_name', models.CharField(default=b'null', max_length=300, primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
