# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIdModel',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField()),
            ],
        ),
    ]
