# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20171126_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobIdModel',
        ),
    ]
