# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_delete_jobidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
            ],
        ),
    ]
