# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_jobidmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobidmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='jobidmodel',
            name='job_name',
            field=models.CharField(default=b'null', max_length=300, primary_key=True, serialize=False),
        ),
    ]
